from typing import TypeAlias
from ._pcmffi import ffi, lib

PROCMAPS_ERROR_T: TypeAlias = int

PROCMAPS_SUCCESS: PROCMAPS_ERROR_T = 0
PROCMAPS_ERROR_OPEN_MAPS_FILE: PROCMAPS_ERROR_T = 1
PROCMAPS_ERROR_READ_MAPS_FILE: PROCMAPS_ERROR_T = 2
PROCMAPS_ERROR_MALLOC_FAIL: PROCMAPS_ERROR_T = 3

PROCMAPS_MAP_TYPE: TypeAlias = int

PROCMAPS_MAP_FILE: PROCMAPS_MAP_TYPE = 0
PROCMAPS_MAP_STACK: PROCMAPS_MAP_TYPE = 1 
PROCMAPS_MAP_STACK_TID: PROCMAPS_MAP_TYPE = 2
PROCMAPS_MAP_VDSO: PROCMAPS_MAP_TYPE = 3
PROCMAPS_MAP_VVAR: PROCMAPS_MAP_TYPE = 4
PROCMAPS_MAP_VSYSCALL: PROCMAPS_MAP_TYPE = 5
PROCMAPS_MAP_HEAP: PROCMAPS_MAP_TYPE = 6
PROCMAPS_MAP_ANON_PRIV: PROCMAPS_MAP_TYPE = 7
PROCMAPS_MAP_ANON_SHMEM: PROCMAPS_MAP_TYPE = 8
PROCMAPS_MAP_ANON_MMAPS: PROCMAPS_MAP_TYPE = 9
PROCMAPS_MAP_OTHER: PROCMAPS_MAP_TYPE = 10

class ProcMaps(object):
    def __init__(self, pid: int = -1) -> None:
        self._pid = pid
    
    @property
    def pid(self) -> int:
        return self._pid
